/**
 * Email integration utilities
 * Supports sending mind maps as email, email templates, and newsletter generation
 */

import type { MindMapTree } from '../types';

interface EmailConfig {
  recipient: string;
  subject: string;
  includeSummary: boolean;
  includePlainText: boolean;
  includeHTML: boolean;
  format: 'summary' | 'detailed' | 'bullet-points' | 'newsletter';
}

/**
 * Open email client with mind map content
 */
export function sendEmail(tree: MindMapTree, config: EmailConfig): void {
  const body = generateEmailBody(tree, config);
  const subject = encodeURIComponent(config.subject || `Mind Map: ${tree.content}`);
  const encodedBody = encodeURIComponent(body);

  // Open default email client
  window.location.href = `mailto:${config.recipient}?subject=${subject}&body=${encodedBody}`;
}

/**
 * Generate email body based on format
 */
function generateEmailBody(tree: MindMapTree, config: EmailConfig): string {
  switch (config.format) {
    case 'summary':
      return generateSummaryEmail(tree, config);
    case 'detailed':
      return generateDetailedEmail(tree, config);
    case 'bullet-points':
      return generateBulletPointsEmail(tree, config);
    case 'newsletter':
      return generateNewsletterEmail(tree, config);
    default:
      return generateSummaryEmail(tree, config);
  }
}

/**
 * Generate summary email format
 */
function generateSummaryEmail(tree: MindMapTree, config: EmailConfig): string {
  const lines: string[] = [];

  lines.push('MIND MAP SUMMARY');
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Title: ${tree.content}`);
  lines.push(`Total Nodes: ${countNodes(tree)}`);
  lines.push(`Depth: ${getDepth(tree)}`);
  lines.push('');

  if (config.includePlainText) {
    lines.push('STRUCTURE:');
    lines.push(generatePlainTextTree(tree, 0));
  }

  if (tree.metadata?.notes) {
    lines.push('');
    lines.push('NOTES:');
    lines.push(tree.metadata.notes);
  }

  return lines.join('\n');
}

/**
 * Generate detailed email format
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function generateDetailedEmail(tree: MindMapTree, _config: EmailConfig): string {
  const lines: string[] = [];

  lines.push('MIND MAP - DETAILED VIEW');
  lines.push('='.repeat(50));
  lines.push('');

  const traverse = (node: MindMapTree, depth: number = 0) => {
    const indent = '  '.repeat(depth);
    const prefix = depth === 0 ? '' : `${indent}• `;

    lines.push(`${prefix}${node.content}`);

    if (node.metadata?.notes) {
      lines.push(`${indent}  Notes: ${node.metadata.notes}`);
    }

    if (node.metadata?.link) {
      lines.push(`${indent}  Link: ${node.metadata.link}`);
    }

    if (node.children && node.children.length > 0) {
      node.children.forEach(child => traverse(child, depth + 1));
    }
  };

  traverse(tree);

  lines.push('');
  lines.push('---');
  lines.push(`Generated by MindMapWeb`);
  lines.push(`Date: ${new Date().toLocaleDateString()}`);

  return lines.join('\n');
}

/**
 * Generate bullet points email format
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function generateBulletPointsEmail(tree: MindMapTree, _config: EmailConfig): string {
  const lines: string[] = [];

  lines.push(`📝 ${tree.content}`);
  lines.push('');

  const traverse = (node: MindMapTree, depth: number = 0) => {
    const indent = depth === 0 ? '' : '  '.repeat(depth - 1) + (depth > 0 ? '• ' : '');

    lines.push(`${indent}${node.content}`);

    if (node.children && node.children.length > 0) {
      node.children.forEach(child => traverse(child, depth + 1));
    }
  };

  if (tree.children) {
    tree.children.forEach(child => traverse(child, 1));
  }

  return lines.join('\n');
}

/**
 * Generate newsletter-style email
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function generateNewsletterEmail(tree: MindMapTree, _config: EmailConfig): string {
  const lines: string[] = [];

  lines.push('╔════════════════════════════════════════╗');
  lines.push('║       MIND MAP NEWSLETTER             ║');
  lines.push('╚════════════════════════════════════════╝');
  lines.push('');
  lines.push(`📊 ${tree.content.toUpperCase()}`);
  lines.push('');
  lines.push('─'.repeat(50));
  lines.push('');

  // Main sections
  if (tree.children && tree.children.length > 0) {
    tree.children.slice(0, 5).forEach((child, index) => {
      lines.push(`${index + 1}. ${child.content.toUpperCase()}`);
      lines.push('');

      if (child.children && child.children.length > 0) {
        child.children.slice(0, 3).forEach(subchild => {
          lines.push(`   • ${subchild.content}`);
        });
      }

      lines.push('');
    });
  }

  lines.push('─'.repeat(50));
  lines.push('');
  lines.push('💡 Quick Stats:');
  lines.push(`   • Total Topics: ${countNodes(tree)}`);
  lines.push(`   • Main Sections: ${tree.children?.length || 0}`);
  lines.push('');
  lines.push('Thank you for reading!');
  lines.push('');
  lines.push('─'.repeat(50));
  lines.push('Generated by MindMapWeb');

  return lines.join('\n');
}

/**
 * Generate plain text tree representation
 */
function generatePlainTextTree(tree: MindMapTree, depth: number): string {
  const lines: string[] = [];
  const indent = '  '.repeat(depth);

  lines.push(`${indent}${tree.content}`);

  if (tree.children && tree.children.length > 0) {
    tree.children.forEach(child => {
      lines.push(generatePlainTextTree(child, depth + 1));
    });
  }

  return lines.join('\n');
}

/**
 * Generate HTML email body
 */
export function generateHTMLEmail(tree: MindMapTree): string {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(tree.content)}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 20px;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .node {
      margin: 10px 0;
      padding: 8px;
      background: #f9fafb;
      border-left: 3px solid #667eea;
      border-radius: 4px;
    }
    .node-children {
      margin-left: 20px;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #6b7280;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🧠 ${escapeHtml(tree.content)}</h1>
  </div>
  <div class="content">
    ${renderNodeHTML(tree)}
  </div>
  <div class="footer">
    <p>Generated by MindMapWeb on ${new Date().toLocaleDateString()}</p>
    <p>Total nodes: ${countNodes(tree)} | Depth: ${getDepth(tree)}</p>
  </div>
</body>
</html>
  `;

  return html;
}

/**
 * Render node as HTML
 */
function renderNodeHTML(node: MindMapTree, depth: number = 0): string {
  const childrenHTML = node.children
    ? node.children.map(child => renderNodeHTML(child, depth + 1)).join('')
    : '';

  return `
    <div class="node" style="margin-left: ${depth * 20}px">
      <strong>${escapeHtml(node.content)}</strong>
      ${node.metadata?.notes ? `<p style="margin: 5px 0; font-size: 12px; color: #6b7280;">${escapeHtml(node.metadata.notes)}</p>` : ''}
    </div>
    ${childrenHTML}
  `;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Count nodes in tree
 */
function countNodes(tree: MindMapTree): number {
  let count = 1;
  if (tree.children) {
    tree.children.forEach(child => {
      count += countNodes(child);
    });
  }
  return count;
}

/**
 * Get tree depth
 */
function getDepth(tree: MindMapTree): number {
  if (!tree.children || tree.children.length === 0) {
    return 1;
  }
  return 1 + Math.max(...tree.children.map(child => getDepth(child)));
}

/**
 * Download email as HTML file
 */
export function downloadEmailHTML(tree: MindMapTree, filename: string = 'mindmap-email.html'): void {
  const html = generateHTMLEmail(tree);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Generate email signature with mind map link
 */
export function generateEmailSignature(tree: MindMapTree): string {
  return `
--
${tree.content}
View Mind Map: ${window.location.href}

Generated by MindMapWeb
  `.trim();
}

/**
 * Export mind map as email template
 */
export function exportEmailTemplate(tree: MindMapTree): void {
  const template = {
    name: `${tree.content} Template`,
    subject: `Update: ${tree.content}`,
    body: generateSummaryEmail(tree, {
      recipient: '',
      subject: '',
      includeSummary: true,
      includePlainText: true,
      includeHTML: false,
      format: 'detailed',
    }),
    html: generateHTMLEmail(tree),
  };

  const blob = new Blob([JSON.stringify(template, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'email-template.json';
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Generate weekly digest email
 */
export function generateWeeklyDigest(tree: MindMapTree, startDate: Date, endDate: Date): string {
  const lines: string[] = [];

  lines.push('WEEKLY MIND MAP DIGEST');
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Period: ${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`);
  lines.push(`Mind Map: ${tree.content}`);
  lines.push('');

  lines.push('KEY UPDATES:');
  lines.push('');

  const traverse = (node: MindMapTree, depth: number = 0) => {
    const createdDate = node.metadata?.created ? new Date(node.metadata.created) : null;
    const modifiedDate = node.metadata?.lastModified ? new Date(node.metadata.lastModified) : null;

    if (createdDate && createdDate >= startDate && createdDate <= endDate) {
      const indent = '  '.repeat(depth);
      lines.push(`${indent}➕ NEW: ${node.content}`);
    }

    if (modifiedDate && modifiedDate >= startDate && modifiedDate <= endDate) {
      const indent = '  '.repeat(depth);
      lines.push(`${indent}✏️  UPDATED: ${node.content}`);
    }

    if (node.children) {
      node.children.forEach(child => traverse(child, depth + 1));
    }
  };

  traverse(tree);

  lines.push('');
  lines.push('─'.repeat(50));
  lines.push(`Total changes this week: ${countNodes(tree)}`);
  lines.push('');
  lines.push('View full mind map: ' + window.location.href);

  return lines.join('\n');
}
